image=apps/media/media-viewer.sh
audio=apps/media/media-viewer.sh
video=apps/media/media-viewer.sh
pdf=apps/media/media-viewer.sh
text=apps/editor/text-editor.sh
browser=apps/browser-picker/browser-picker.sh
